algo: ppo
ppo_epochs: 4 # Number of epochs for PPO
ppo_batch_size: 256
ppo_clip_eps: 0.2 # Clipping epsilon for PPO
frames: 2056 # Number of frames before update !!!!!! decrease to 1024 --> number of steps in one call to collect_experiences
# CRITICAL: Changed from 2048 to 2056 (so it's traj_per_batch * (seqdur + 1))
