defaults:
    - _self_  

room_type_green: "dot" # Options: "line", "plus", "dot", "extrinsic_goal"
new_obj_loc: [7, 2]

training:
  num_trajs: 3000 # trajectories to train on in novel env
  saving_interval: 25 # batches between saving
  analysis_interval: 25 # batches between logging
  lr_trials: 2 
  lrgroups: [0, 1, 2]
  resetOptimizer: False
  continueTraining: False

testing:
  trajs: 8 # trajectories to inspect for test trial. Must be smaller than trajs_per_batch in training for now
  ctrl_locs: [[2, 5], [4, 7], [11, 3], [13, 5]]
  whichPhase: 0 # which phase to analyze in quantifyObjectLearning
  start_random: False
  start_up_bound: [12, 6] # [8, 14] for away
  start_low_bound: [1, 1] # [1, 7] for away

analysis:
  objLearning_fig: True
  traj_fig: True
  occupancy: True