defaults:
    - _self_  

room_type_green: "line" # Options: "line", "plus", "dot", "extrinsic_goal"

training:
  num_trajs: 3000 # trajectories to train on in novel env
  saving_interval: 25 # batches between saving
  analysis_interval: 25 # batches between logging
  lr_trials: 2 
  lrgroups: [0, 1, 2]
  resetOptimizer: False
  continueTraining: False

testing:
  trajs: 6 # trajectories to inspect for test trial. Must be smaller than trajs_per_batch in training for now
  control_location: [4, 7]
  whichPhase: 0 # which phase to analyze in quantifyObjectLearning

analysis:
  objLearning_fig: True
  traj_fig: True
  occupancy: True